from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# This is where we bridge the API to your LangChain logic
from main_agent import agent_executor

app = FastAPI(title="AetherFlow AI API")

# CORS allows your React frontend (running on a different port) to talk to this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, change "*" to your actual React app URL (e.g., "http://localhost:3000")
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class AnalysisRequest(BaseModel):
    sku: str

@app.post("/api/analyze")
async def analyze_sku(request: AnalysisRequest):
    """
    This endpoint receives an SKU from React, passes it to LangChain, 
    and returns the agent's final decision.
    """
    try:
        # Run your actual LangChain agent
        response = agent_executor.invoke({
            "input": f"Please analyze {request.sku} and take necessary actions."
        })
        
        # Return the final string generated by the LLM
        return {
            "status": "success", 
            "agent_output": response["output"]
        }
    except Exception as e:
        # Handle API keys errors or unexpected crashes cleanly
        return {
            "status": "error", 
            "message": str(e)
        }